# Configuration pour le pipeline ETL Sufosat

# Paramètres extract 
extract_sufosat:
  s3_prefix: "dataeng/sufosat_data/"
  s3_filename: "forest-clearcuts_mainland-france_sufosat_dates_v3.tif"
  s3_sufosat_metadata: "forest-clearcuts_mainland-france_sufosat_dates_v3-metadata.json"
  zendo_filename: "forest-clearcuts_mainland-france_sufosat_dates_v3.tif"
  zendo_id: "15004634"

# Paramètres transform
transform_sufosat:
  download_path: "data_temp/"
  export_filename: "sufosat_clear_cuts_v3.geoparquet"
  filtered_raster: "forest-clearcuts_mainland-france_sufosat_dates_v3_filtered.tif"
  polygonized_data: "forest-clearcuts_mainland-france_sufosat_dates_v3.shp"